### ISSUE TITLE
Black tables are invisible in night mode.

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki21__PFP_table#5]
Should be a simple fix.

If you give tables the attribute **border="1"** instead of putting _border: 1px solid black_ all through the table, that should do it.

**Comment by ijgnd** [comment]
Thanks for your report.

I don't know much about css and html. I just tried your suggestion but it doesn't work for me: When I use a new profile and insert a table from my add-on and replace all occurences of `border: 1px solid black` with `border=1` it doesn't work. I see no borders, the source code from my add-on is at [1], and then I modified it according to your guide so that it it as listed under [2]. [2] doesn't show any borders.

<br />

For the table border I found the variable `currentcolor` (`border:1px solid currentColor;`) which renders the border in black in regular Anki whereas it's white during nightmode. That's good. But this property doesn't work on `tr`, `th`, or `td`elements. So no lines between cells are shown for me.

<br />

Did I miss something? 

I would try with css - in my table add-on set as styling "css1" and then I would put this css into my card templates:

```css
.table_class_one {
 font-size: 85%; 
 border-collapse: collapse; 
 border: 1px solid black;
}

.night_mode .table_class_one {
 border: 1px solid white;
}

.table_class_one th {
width:50%;  
padding:2px; 
border: 1px solid black;
}

.night_mode .table_class_one th {
border: 1px solid white;
}

.table_class_one td {
width:50%;  
padding:2px; 
border: 1px solid black;
}

.night_mode .table_class_one td {
border: 1px solid white;
}
```

<br />
<br />
<br />

-----

[1] original output

```html
<table style="font-size: 85%; border-collapse: collapse; border: 1px solid black;">
 <thead>
  <tr>
   <th style="width:50%;  padding:2px; border: 1px solid black;">
    head1
   </th>
   <th style="width:50%;  padding:2px; border: 1px solid black;">
    head2
   </th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td style="width:50%;  padding:2px; border: 1px solid black;">
    data1
   </td>
   <td style="width:50%;  padding:2px; border: 1px solid black;">
    data2
   </td>
  </tr>
  <tr>
   <td style="width:50%;  padding:2px; border: 1px solid black;">
    data1
   </td>
   <td style="width:50%;  padding:2px; border: 1px solid black;">
    data2
   </td>
  </tr>
 </tbody>
</table>
```
<br />
<br />
<br />

[2] modification according to your suggestion that doesn't show any borders

```html
<table 1";"="" style="font-size: 85%; border-collapse: collapse; border: 1">
 <thead>
  <tr>
   <th style="width:50%;  padding:2px; border: 1;">
    head1
   </th>
   <th style="width:50%;  padding:2px; border: 1;">
    head2
   </th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td style="width:50%;  padding:2px; border: 1;">
    data1
   </td>
   <td style="width:50%;  padding:2px; border: 1;">
    data2
   </td>
  </tr>
  <tr>
   <td style="width:50%;  padding:2px; border: 1;">
    data1
   </td>
   <td style='width:50%;  padding:2px; border: "1";'>
    data2
   </td>
  </tr>
 </tbody>
</table>
```

You could insert
